# coding: utf-8

"""
    Bumbal Client Api

    Bumbal API documentation  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: gerb@bumbal.eu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from bumbal.configuration import Configuration


class AddressReverseGeoCodeArguments(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'min_accuracy': 'float',
        'distance': 'int',
        'latitude': 'str',
        'longitude': 'str'
    }

    attribute_map = {
        'min_accuracy': 'min_accuracy',
        'distance': 'distance',
        'latitude': 'latitude',
        'longitude': 'longitude'
    }

    def __init__(self, min_accuracy=None, distance=None, latitude=None, longitude=None, _configuration=None):  # noqa: E501
        """AddressReverseGeoCodeArguments - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._min_accuracy = None
        self._distance = None
        self._latitude = None
        self._longitude = None
        self.discriminator = None

        if min_accuracy is not None:
            self.min_accuracy = min_accuracy
        if distance is not None:
            self.distance = distance
        if latitude is not None:
            self.latitude = latitude
        if longitude is not None:
            self.longitude = longitude

    @property
    def min_accuracy(self):
        """Gets the min_accuracy of this AddressReverseGeoCodeArguments.  # noqa: E501

          # noqa: E501

        :return: The min_accuracy of this AddressReverseGeoCodeArguments.  # noqa: E501
        :rtype: float
        """
        return self._min_accuracy

    @min_accuracy.setter
    def min_accuracy(self, min_accuracy):
        """Sets the min_accuracy of this AddressReverseGeoCodeArguments.

          # noqa: E501

        :param min_accuracy: The min_accuracy of this AddressReverseGeoCodeArguments.  # noqa: E501
        :type: float
        """

        self._min_accuracy = min_accuracy

    @property
    def distance(self):
        """Gets the distance of this AddressReverseGeoCodeArguments.  # noqa: E501

          # noqa: E501

        :return: The distance of this AddressReverseGeoCodeArguments.  # noqa: E501
        :rtype: int
        """
        return self._distance

    @distance.setter
    def distance(self, distance):
        """Sets the distance of this AddressReverseGeoCodeArguments.

          # noqa: E501

        :param distance: The distance of this AddressReverseGeoCodeArguments.  # noqa: E501
        :type: int
        """

        self._distance = distance

    @property
    def latitude(self):
        """Gets the latitude of this AddressReverseGeoCodeArguments.  # noqa: E501

          # noqa: E501

        :return: The latitude of this AddressReverseGeoCodeArguments.  # noqa: E501
        :rtype: str
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this AddressReverseGeoCodeArguments.

          # noqa: E501

        :param latitude: The latitude of this AddressReverseGeoCodeArguments.  # noqa: E501
        :type: str
        """

        self._latitude = latitude

    @property
    def longitude(self):
        """Gets the longitude of this AddressReverseGeoCodeArguments.  # noqa: E501

          # noqa: E501

        :return: The longitude of this AddressReverseGeoCodeArguments.  # noqa: E501
        :rtype: str
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this AddressReverseGeoCodeArguments.

          # noqa: E501

        :param longitude: The longitude of this AddressReverseGeoCodeArguments.  # noqa: E501
        :type: str
        """

        self._longitude = longitude

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AddressReverseGeoCodeArguments, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AddressReverseGeoCodeArguments):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AddressReverseGeoCodeArguments):
            return True

        return self.to_dict() != other.to_dict()
