# coding: utf-8

"""
    Bumbal Client Api

    Bumbal API documentation  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: gerb@bumbal.eu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from bumbal.configuration import Configuration


class BrandModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'tags': 'list[TagModel]',
        'links': 'list[LinkModel]',
        'meta_data': 'list[MetaDataModel]',
        'brand_colours': 'list[BrandColourModel]',
        'files': 'list[FileModel]',
        'portal_settings': 'list[PortalSettingModel]',
        'brand_created_by': 'UsersModel',
        'brand_updated_by': 'UsersModel',
        'brand_created_at': 'datetime',
        'brand_updated_at': 'datetime'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'tags': 'tags',
        'links': 'links',
        'meta_data': 'meta_data',
        'brand_colours': 'brand_colours',
        'files': 'files',
        'portal_settings': 'portal_settings',
        'brand_created_by': 'brand_created_by',
        'brand_updated_by': 'brand_updated_by',
        'brand_created_at': 'brand_created_at',
        'brand_updated_at': 'brand_updated_at'
    }

    def __init__(self, id=None, name=None, tags=None, links=None, meta_data=None, brand_colours=None, files=None, portal_settings=None, brand_created_by=None, brand_updated_by=None, brand_created_at=None, brand_updated_at=None, _configuration=None):  # noqa: E501
        """BrandModel - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._name = None
        self._tags = None
        self._links = None
        self._meta_data = None
        self._brand_colours = None
        self._files = None
        self._portal_settings = None
        self._brand_created_by = None
        self._brand_updated_by = None
        self._brand_created_at = None
        self._brand_updated_at = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if tags is not None:
            self.tags = tags
        if links is not None:
            self.links = links
        if meta_data is not None:
            self.meta_data = meta_data
        if brand_colours is not None:
            self.brand_colours = brand_colours
        if files is not None:
            self.files = files
        if portal_settings is not None:
            self.portal_settings = portal_settings
        if brand_created_by is not None:
            self.brand_created_by = brand_created_by
        if brand_updated_by is not None:
            self.brand_updated_by = brand_updated_by
        if brand_created_at is not None:
            self.brand_created_at = brand_created_at
        if brand_updated_at is not None:
            self.brand_updated_at = brand_updated_at

    @property
    def id(self):
        """Gets the id of this BrandModel.  # noqa: E501

        Unique Identifier  # noqa: E501

        :return: The id of this BrandModel.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this BrandModel.

        Unique Identifier  # noqa: E501

        :param id: The id of this BrandModel.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this BrandModel.  # noqa: E501

        Name of brand  # noqa: E501

        :return: The name of this BrandModel.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this BrandModel.

        Name of brand  # noqa: E501

        :param name: The name of this BrandModel.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def tags(self):
        """Gets the tags of this BrandModel.  # noqa: E501

          # noqa: E501

        :return: The tags of this BrandModel.  # noqa: E501
        :rtype: list[TagModel]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this BrandModel.

          # noqa: E501

        :param tags: The tags of this BrandModel.  # noqa: E501
        :type: list[TagModel]
        """

        self._tags = tags

    @property
    def links(self):
        """Gets the links of this BrandModel.  # noqa: E501

          # noqa: E501

        :return: The links of this BrandModel.  # noqa: E501
        :rtype: list[LinkModel]
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this BrandModel.

          # noqa: E501

        :param links: The links of this BrandModel.  # noqa: E501
        :type: list[LinkModel]
        """

        self._links = links

    @property
    def meta_data(self):
        """Gets the meta_data of this BrandModel.  # noqa: E501

          # noqa: E501

        :return: The meta_data of this BrandModel.  # noqa: E501
        :rtype: list[MetaDataModel]
        """
        return self._meta_data

    @meta_data.setter
    def meta_data(self, meta_data):
        """Sets the meta_data of this BrandModel.

          # noqa: E501

        :param meta_data: The meta_data of this BrandModel.  # noqa: E501
        :type: list[MetaDataModel]
        """

        self._meta_data = meta_data

    @property
    def brand_colours(self):
        """Gets the brand_colours of this BrandModel.  # noqa: E501

          # noqa: E501

        :return: The brand_colours of this BrandModel.  # noqa: E501
        :rtype: list[BrandColourModel]
        """
        return self._brand_colours

    @brand_colours.setter
    def brand_colours(self, brand_colours):
        """Sets the brand_colours of this BrandModel.

          # noqa: E501

        :param brand_colours: The brand_colours of this BrandModel.  # noqa: E501
        :type: list[BrandColourModel]
        """

        self._brand_colours = brand_colours

    @property
    def files(self):
        """Gets the files of this BrandModel.  # noqa: E501

          # noqa: E501

        :return: The files of this BrandModel.  # noqa: E501
        :rtype: list[FileModel]
        """
        return self._files

    @files.setter
    def files(self, files):
        """Sets the files of this BrandModel.

          # noqa: E501

        :param files: The files of this BrandModel.  # noqa: E501
        :type: list[FileModel]
        """

        self._files = files

    @property
    def portal_settings(self):
        """Gets the portal_settings of this BrandModel.  # noqa: E501

          # noqa: E501

        :return: The portal_settings of this BrandModel.  # noqa: E501
        :rtype: list[PortalSettingModel]
        """
        return self._portal_settings

    @portal_settings.setter
    def portal_settings(self, portal_settings):
        """Sets the portal_settings of this BrandModel.

          # noqa: E501

        :param portal_settings: The portal_settings of this BrandModel.  # noqa: E501
        :type: list[PortalSettingModel]
        """

        self._portal_settings = portal_settings

    @property
    def brand_created_by(self):
        """Gets the brand_created_by of this BrandModel.  # noqa: E501

          # noqa: E501

        :return: The brand_created_by of this BrandModel.  # noqa: E501
        :rtype: UsersModel
        """
        return self._brand_created_by

    @brand_created_by.setter
    def brand_created_by(self, brand_created_by):
        """Sets the brand_created_by of this BrandModel.

          # noqa: E501

        :param brand_created_by: The brand_created_by of this BrandModel.  # noqa: E501
        :type: UsersModel
        """

        self._brand_created_by = brand_created_by

    @property
    def brand_updated_by(self):
        """Gets the brand_updated_by of this BrandModel.  # noqa: E501

          # noqa: E501

        :return: The brand_updated_by of this BrandModel.  # noqa: E501
        :rtype: UsersModel
        """
        return self._brand_updated_by

    @brand_updated_by.setter
    def brand_updated_by(self, brand_updated_by):
        """Sets the brand_updated_by of this BrandModel.

          # noqa: E501

        :param brand_updated_by: The brand_updated_by of this BrandModel.  # noqa: E501
        :type: UsersModel
        """

        self._brand_updated_by = brand_updated_by

    @property
    def brand_created_at(self):
        """Gets the brand_created_at of this BrandModel.  # noqa: E501

        created_at date time  # noqa: E501

        :return: The brand_created_at of this BrandModel.  # noqa: E501
        :rtype: datetime
        """
        return self._brand_created_at

    @brand_created_at.setter
    def brand_created_at(self, brand_created_at):
        """Sets the brand_created_at of this BrandModel.

        created_at date time  # noqa: E501

        :param brand_created_at: The brand_created_at of this BrandModel.  # noqa: E501
        :type: datetime
        """

        self._brand_created_at = brand_created_at

    @property
    def brand_updated_at(self):
        """Gets the brand_updated_at of this BrandModel.  # noqa: E501

        updated_at date time  # noqa: E501

        :return: The brand_updated_at of this BrandModel.  # noqa: E501
        :rtype: datetime
        """
        return self._brand_updated_at

    @brand_updated_at.setter
    def brand_updated_at(self, brand_updated_at):
        """Sets the brand_updated_at of this BrandModel.

        updated_at date time  # noqa: E501

        :param brand_updated_at: The brand_updated_at of this BrandModel.  # noqa: E501
        :type: datetime
        """

        self._brand_updated_at = brand_updated_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BrandModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BrandModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BrandModel):
            return True

        return self.to_dict() != other.to_dict()
