# coding: utf-8

"""
    Bumbal Client Api

    Bumbal API documentation  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: gerb@bumbal.eu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from bumbal.configuration import Configuration


class BrandOptionsModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'include_tags': 'bool',
        'include_brand_colours': 'bool',
        'include_links': 'bool',
        'include_record_info': 'bool',
        'include_files': 'bool',
        'include_meta_data': 'bool',
        'include_notes': 'bool',
        'include_portal_settings': 'bool'
    }

    attribute_map = {
        'include_tags': 'include_tags',
        'include_brand_colours': 'include_brand_colours',
        'include_links': 'include_links',
        'include_record_info': 'include_record_info',
        'include_files': 'include_files',
        'include_meta_data': 'include_meta_data',
        'include_notes': 'include_notes',
        'include_portal_settings': 'include_portal_settings'
    }

    def __init__(self, include_tags=None, include_brand_colours=None, include_links=None, include_record_info=None, include_files=None, include_meta_data=None, include_notes=None, include_portal_settings=None, _configuration=None):  # noqa: E501
        """BrandOptionsModel - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._include_tags = None
        self._include_brand_colours = None
        self._include_links = None
        self._include_record_info = None
        self._include_files = None
        self._include_meta_data = None
        self._include_notes = None
        self._include_portal_settings = None
        self.discriminator = None

        if include_tags is not None:
            self.include_tags = include_tags
        if include_brand_colours is not None:
            self.include_brand_colours = include_brand_colours
        if include_links is not None:
            self.include_links = include_links
        if include_record_info is not None:
            self.include_record_info = include_record_info
        if include_files is not None:
            self.include_files = include_files
        if include_meta_data is not None:
            self.include_meta_data = include_meta_data
        if include_notes is not None:
            self.include_notes = include_notes
        if include_portal_settings is not None:
            self.include_portal_settings = include_portal_settings

    @property
    def include_tags(self):
        """Gets the include_tags of this BrandOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_tags of this BrandOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_tags

    @include_tags.setter
    def include_tags(self, include_tags):
        """Sets the include_tags of this BrandOptionsModel.

          # noqa: E501

        :param include_tags: The include_tags of this BrandOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_tags = include_tags

    @property
    def include_brand_colours(self):
        """Gets the include_brand_colours of this BrandOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_brand_colours of this BrandOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_brand_colours

    @include_brand_colours.setter
    def include_brand_colours(self, include_brand_colours):
        """Sets the include_brand_colours of this BrandOptionsModel.

          # noqa: E501

        :param include_brand_colours: The include_brand_colours of this BrandOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_brand_colours = include_brand_colours

    @property
    def include_links(self):
        """Gets the include_links of this BrandOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_links of this BrandOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_links

    @include_links.setter
    def include_links(self, include_links):
        """Sets the include_links of this BrandOptionsModel.

          # noqa: E501

        :param include_links: The include_links of this BrandOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_links = include_links

    @property
    def include_record_info(self):
        """Gets the include_record_info of this BrandOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_record_info of this BrandOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_record_info

    @include_record_info.setter
    def include_record_info(self, include_record_info):
        """Sets the include_record_info of this BrandOptionsModel.

          # noqa: E501

        :param include_record_info: The include_record_info of this BrandOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_record_info = include_record_info

    @property
    def include_files(self):
        """Gets the include_files of this BrandOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_files of this BrandOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_files

    @include_files.setter
    def include_files(self, include_files):
        """Sets the include_files of this BrandOptionsModel.

          # noqa: E501

        :param include_files: The include_files of this BrandOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_files = include_files

    @property
    def include_meta_data(self):
        """Gets the include_meta_data of this BrandOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_meta_data of this BrandOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_meta_data

    @include_meta_data.setter
    def include_meta_data(self, include_meta_data):
        """Sets the include_meta_data of this BrandOptionsModel.

          # noqa: E501

        :param include_meta_data: The include_meta_data of this BrandOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_meta_data = include_meta_data

    @property
    def include_notes(self):
        """Gets the include_notes of this BrandOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_notes of this BrandOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_notes

    @include_notes.setter
    def include_notes(self, include_notes):
        """Sets the include_notes of this BrandOptionsModel.

          # noqa: E501

        :param include_notes: The include_notes of this BrandOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_notes = include_notes

    @property
    def include_portal_settings(self):
        """Gets the include_portal_settings of this BrandOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_portal_settings of this BrandOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_portal_settings

    @include_portal_settings.setter
    def include_portal_settings(self, include_portal_settings):
        """Sets the include_portal_settings of this BrandOptionsModel.

          # noqa: E501

        :param include_portal_settings: The include_portal_settings of this BrandOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_portal_settings = include_portal_settings

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BrandOptionsModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BrandOptionsModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BrandOptionsModel):
            return True

        return self.to_dict() != other.to_dict()
