# coding: utf-8

"""
    Bumbal Client Api

    Bumbal API documentation  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: gerb@bumbal.eu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from bumbal.configuration import Configuration


class CompartmentFiltersModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'updated_at_since': 'datetime',
        'updated_at_till': 'datetime',
        'nr': 'list[str]'
    }

    attribute_map = {
        'updated_at_since': 'updated_at_since',
        'updated_at_till': 'updated_at_till',
        'nr': 'nr'
    }

    def __init__(self, updated_at_since=None, updated_at_till=None, nr=None, _configuration=None):  # noqa: E501
        """CompartmentFiltersModel - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._updated_at_since = None
        self._updated_at_till = None
        self._nr = None
        self.discriminator = None

        if updated_at_since is not None:
            self.updated_at_since = updated_at_since
        if updated_at_till is not None:
            self.updated_at_till = updated_at_till
        if nr is not None:
            self.nr = nr

    @property
    def updated_at_since(self):
        """Gets the updated_at_since of this CompartmentFiltersModel.  # noqa: E501

        Show updated since  # noqa: E501

        :return: The updated_at_since of this CompartmentFiltersModel.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at_since

    @updated_at_since.setter
    def updated_at_since(self, updated_at_since):
        """Sets the updated_at_since of this CompartmentFiltersModel.

        Show updated since  # noqa: E501

        :param updated_at_since: The updated_at_since of this CompartmentFiltersModel.  # noqa: E501
        :type: datetime
        """

        self._updated_at_since = updated_at_since

    @property
    def updated_at_till(self):
        """Gets the updated_at_till of this CompartmentFiltersModel.  # noqa: E501

        Show updated till  # noqa: E501

        :return: The updated_at_till of this CompartmentFiltersModel.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at_till

    @updated_at_till.setter
    def updated_at_till(self, updated_at_till):
        """Sets the updated_at_till of this CompartmentFiltersModel.

        Show updated till  # noqa: E501

        :param updated_at_till: The updated_at_till of this CompartmentFiltersModel.  # noqa: E501
        :type: datetime
        """

        self._updated_at_till = updated_at_till

    @property
    def nr(self):
        """Gets the nr of this CompartmentFiltersModel.  # noqa: E501

        Compartment nr  # noqa: E501

        :return: The nr of this CompartmentFiltersModel.  # noqa: E501
        :rtype: list[str]
        """
        return self._nr

    @nr.setter
    def nr(self, nr):
        """Sets the nr of this CompartmentFiltersModel.

        Compartment nr  # noqa: E501

        :param nr: The nr of this CompartmentFiltersModel.  # noqa: E501
        :type: list[str]
        """

        self._nr = nr

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CompartmentFiltersModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CompartmentFiltersModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CompartmentFiltersModel):
            return True

        return self.to_dict() != other.to_dict()
