# coding: utf-8

"""
    Bumbal Client Api

    Bumbal API documentation  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: gerb@bumbal.eu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from bumbal.configuration import Configuration


class DriverOptionsModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'include_record_info': 'bool',
        'include_meta_data': 'bool',
        'include_tags': 'bool',
        'include_tag_names': 'bool',
        'include_tag_ids': 'bool',
        'include_addresses': 'bool',
        'include_links': 'bool',
        'include_notes': 'bool',
        'include_zones': 'bool',
        'include_zone_names': 'bool',
        'include_zone_ids': 'bool',
        'include_files': 'bool',
        'include_driver_record_info': 'bool',
        'include_driver_meta_data': 'bool',
        'include_driver_tags': 'bool',
        'include_driver_tag_type_names': 'bool',
        'include_driver_links': 'bool',
        'include_driver_notes': 'bool',
        'include_driver_note_tags': 'bool'
    }

    attribute_map = {
        'include_record_info': 'include_record_info',
        'include_meta_data': 'include_meta_data',
        'include_tags': 'include_tags',
        'include_tag_names': 'include_tag_names',
        'include_tag_ids': 'include_tag_ids',
        'include_addresses': 'include_addresses',
        'include_links': 'include_links',
        'include_notes': 'include_notes',
        'include_zones': 'include_zones',
        'include_zone_names': 'include_zone_names',
        'include_zone_ids': 'include_zone_ids',
        'include_files': 'include_files',
        'include_driver_record_info': 'include_driver_record_info',
        'include_driver_meta_data': 'include_driver_meta_data',
        'include_driver_tags': 'include_driver_tags',
        'include_driver_tag_type_names': 'include_driver_tag_type_names',
        'include_driver_links': 'include_driver_links',
        'include_driver_notes': 'include_driver_notes',
        'include_driver_note_tags': 'include_driver_note_tags'
    }

    def __init__(self, include_record_info=None, include_meta_data=None, include_tags=None, include_tag_names=None, include_tag_ids=None, include_addresses=None, include_links=None, include_notes=None, include_zones=None, include_zone_names=None, include_zone_ids=None, include_files=None, include_driver_record_info=None, include_driver_meta_data=None, include_driver_tags=None, include_driver_tag_type_names=None, include_driver_links=None, include_driver_notes=None, include_driver_note_tags=None, _configuration=None):  # noqa: E501
        """DriverOptionsModel - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._include_record_info = None
        self._include_meta_data = None
        self._include_tags = None
        self._include_tag_names = None
        self._include_tag_ids = None
        self._include_addresses = None
        self._include_links = None
        self._include_notes = None
        self._include_zones = None
        self._include_zone_names = None
        self._include_zone_ids = None
        self._include_files = None
        self._include_driver_record_info = None
        self._include_driver_meta_data = None
        self._include_driver_tags = None
        self._include_driver_tag_type_names = None
        self._include_driver_links = None
        self._include_driver_notes = None
        self._include_driver_note_tags = None
        self.discriminator = None

        if include_record_info is not None:
            self.include_record_info = include_record_info
        if include_meta_data is not None:
            self.include_meta_data = include_meta_data
        if include_tags is not None:
            self.include_tags = include_tags
        if include_tag_names is not None:
            self.include_tag_names = include_tag_names
        if include_tag_ids is not None:
            self.include_tag_ids = include_tag_ids
        if include_addresses is not None:
            self.include_addresses = include_addresses
        if include_links is not None:
            self.include_links = include_links
        if include_notes is not None:
            self.include_notes = include_notes
        if include_zones is not None:
            self.include_zones = include_zones
        if include_zone_names is not None:
            self.include_zone_names = include_zone_names
        if include_zone_ids is not None:
            self.include_zone_ids = include_zone_ids
        if include_files is not None:
            self.include_files = include_files
        if include_driver_record_info is not None:
            self.include_driver_record_info = include_driver_record_info
        if include_driver_meta_data is not None:
            self.include_driver_meta_data = include_driver_meta_data
        if include_driver_tags is not None:
            self.include_driver_tags = include_driver_tags
        if include_driver_tag_type_names is not None:
            self.include_driver_tag_type_names = include_driver_tag_type_names
        if include_driver_links is not None:
            self.include_driver_links = include_driver_links
        if include_driver_notes is not None:
            self.include_driver_notes = include_driver_notes
        if include_driver_note_tags is not None:
            self.include_driver_note_tags = include_driver_note_tags

    @property
    def include_record_info(self):
        """Gets the include_record_info of this DriverOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_record_info of this DriverOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_record_info

    @include_record_info.setter
    def include_record_info(self, include_record_info):
        """Sets the include_record_info of this DriverOptionsModel.

          # noqa: E501

        :param include_record_info: The include_record_info of this DriverOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_record_info = include_record_info

    @property
    def include_meta_data(self):
        """Gets the include_meta_data of this DriverOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_meta_data of this DriverOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_meta_data

    @include_meta_data.setter
    def include_meta_data(self, include_meta_data):
        """Sets the include_meta_data of this DriverOptionsModel.

          # noqa: E501

        :param include_meta_data: The include_meta_data of this DriverOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_meta_data = include_meta_data

    @property
    def include_tags(self):
        """Gets the include_tags of this DriverOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_tags of this DriverOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_tags

    @include_tags.setter
    def include_tags(self, include_tags):
        """Sets the include_tags of this DriverOptionsModel.

          # noqa: E501

        :param include_tags: The include_tags of this DriverOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_tags = include_tags

    @property
    def include_tag_names(self):
        """Gets the include_tag_names of this DriverOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_tag_names of this DriverOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_tag_names

    @include_tag_names.setter
    def include_tag_names(self, include_tag_names):
        """Sets the include_tag_names of this DriverOptionsModel.

          # noqa: E501

        :param include_tag_names: The include_tag_names of this DriverOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_tag_names = include_tag_names

    @property
    def include_tag_ids(self):
        """Gets the include_tag_ids of this DriverOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_tag_ids of this DriverOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_tag_ids

    @include_tag_ids.setter
    def include_tag_ids(self, include_tag_ids):
        """Sets the include_tag_ids of this DriverOptionsModel.

          # noqa: E501

        :param include_tag_ids: The include_tag_ids of this DriverOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_tag_ids = include_tag_ids

    @property
    def include_addresses(self):
        """Gets the include_addresses of this DriverOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_addresses of this DriverOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_addresses

    @include_addresses.setter
    def include_addresses(self, include_addresses):
        """Sets the include_addresses of this DriverOptionsModel.

          # noqa: E501

        :param include_addresses: The include_addresses of this DriverOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_addresses = include_addresses

    @property
    def include_links(self):
        """Gets the include_links of this DriverOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_links of this DriverOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_links

    @include_links.setter
    def include_links(self, include_links):
        """Sets the include_links of this DriverOptionsModel.

          # noqa: E501

        :param include_links: The include_links of this DriverOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_links = include_links

    @property
    def include_notes(self):
        """Gets the include_notes of this DriverOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_notes of this DriverOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_notes

    @include_notes.setter
    def include_notes(self, include_notes):
        """Sets the include_notes of this DriverOptionsModel.

          # noqa: E501

        :param include_notes: The include_notes of this DriverOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_notes = include_notes

    @property
    def include_zones(self):
        """Gets the include_zones of this DriverOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_zones of this DriverOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_zones

    @include_zones.setter
    def include_zones(self, include_zones):
        """Sets the include_zones of this DriverOptionsModel.

          # noqa: E501

        :param include_zones: The include_zones of this DriverOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_zones = include_zones

    @property
    def include_zone_names(self):
        """Gets the include_zone_names of this DriverOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_zone_names of this DriverOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_zone_names

    @include_zone_names.setter
    def include_zone_names(self, include_zone_names):
        """Sets the include_zone_names of this DriverOptionsModel.

          # noqa: E501

        :param include_zone_names: The include_zone_names of this DriverOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_zone_names = include_zone_names

    @property
    def include_zone_ids(self):
        """Gets the include_zone_ids of this DriverOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_zone_ids of this DriverOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_zone_ids

    @include_zone_ids.setter
    def include_zone_ids(self, include_zone_ids):
        """Sets the include_zone_ids of this DriverOptionsModel.

          # noqa: E501

        :param include_zone_ids: The include_zone_ids of this DriverOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_zone_ids = include_zone_ids

    @property
    def include_files(self):
        """Gets the include_files of this DriverOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_files of this DriverOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_files

    @include_files.setter
    def include_files(self, include_files):
        """Sets the include_files of this DriverOptionsModel.

          # noqa: E501

        :param include_files: The include_files of this DriverOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_files = include_files

    @property
    def include_driver_record_info(self):
        """Gets the include_driver_record_info of this DriverOptionsModel.  # noqa: E501

        Deprecated! Use include_record_info instead  # noqa: E501

        :return: The include_driver_record_info of this DriverOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_driver_record_info

    @include_driver_record_info.setter
    def include_driver_record_info(self, include_driver_record_info):
        """Sets the include_driver_record_info of this DriverOptionsModel.

        Deprecated! Use include_record_info instead  # noqa: E501

        :param include_driver_record_info: The include_driver_record_info of this DriverOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_driver_record_info = include_driver_record_info

    @property
    def include_driver_meta_data(self):
        """Gets the include_driver_meta_data of this DriverOptionsModel.  # noqa: E501

        Deprecated! Use include_meta_data instead  # noqa: E501

        :return: The include_driver_meta_data of this DriverOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_driver_meta_data

    @include_driver_meta_data.setter
    def include_driver_meta_data(self, include_driver_meta_data):
        """Sets the include_driver_meta_data of this DriverOptionsModel.

        Deprecated! Use include_meta_data instead  # noqa: E501

        :param include_driver_meta_data: The include_driver_meta_data of this DriverOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_driver_meta_data = include_driver_meta_data

    @property
    def include_driver_tags(self):
        """Gets the include_driver_tags of this DriverOptionsModel.  # noqa: E501

        Deprecated! Use include_tags instead  # noqa: E501

        :return: The include_driver_tags of this DriverOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_driver_tags

    @include_driver_tags.setter
    def include_driver_tags(self, include_driver_tags):
        """Sets the include_driver_tags of this DriverOptionsModel.

        Deprecated! Use include_tags instead  # noqa: E501

        :param include_driver_tags: The include_driver_tags of this DriverOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_driver_tags = include_driver_tags

    @property
    def include_driver_tag_type_names(self):
        """Gets the include_driver_tag_type_names of this DriverOptionsModel.  # noqa: E501

        Deprecated! Use include_tag_names instead  # noqa: E501

        :return: The include_driver_tag_type_names of this DriverOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_driver_tag_type_names

    @include_driver_tag_type_names.setter
    def include_driver_tag_type_names(self, include_driver_tag_type_names):
        """Sets the include_driver_tag_type_names of this DriverOptionsModel.

        Deprecated! Use include_tag_names instead  # noqa: E501

        :param include_driver_tag_type_names: The include_driver_tag_type_names of this DriverOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_driver_tag_type_names = include_driver_tag_type_names

    @property
    def include_driver_links(self):
        """Gets the include_driver_links of this DriverOptionsModel.  # noqa: E501

        Deprecated! Use include_links instead  # noqa: E501

        :return: The include_driver_links of this DriverOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_driver_links

    @include_driver_links.setter
    def include_driver_links(self, include_driver_links):
        """Sets the include_driver_links of this DriverOptionsModel.

        Deprecated! Use include_links instead  # noqa: E501

        :param include_driver_links: The include_driver_links of this DriverOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_driver_links = include_driver_links

    @property
    def include_driver_notes(self):
        """Gets the include_driver_notes of this DriverOptionsModel.  # noqa: E501

        Deprecated! Use include_notes instead  # noqa: E501

        :return: The include_driver_notes of this DriverOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_driver_notes

    @include_driver_notes.setter
    def include_driver_notes(self, include_driver_notes):
        """Sets the include_driver_notes of this DriverOptionsModel.

        Deprecated! Use include_notes instead  # noqa: E501

        :param include_driver_notes: The include_driver_notes of this DriverOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_driver_notes = include_driver_notes

    @property
    def include_driver_note_tags(self):
        """Gets the include_driver_note_tags of this DriverOptionsModel.  # noqa: E501

        Deprecated! Use include_notes + include_tags instead  # noqa: E501

        :return: The include_driver_note_tags of this DriverOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_driver_note_tags

    @include_driver_note_tags.setter
    def include_driver_note_tags(self, include_driver_note_tags):
        """Sets the include_driver_note_tags of this DriverOptionsModel.

        Deprecated! Use include_notes + include_tags instead  # noqa: E501

        :param include_driver_note_tags: The include_driver_note_tags of this DriverOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_driver_note_tags = include_driver_note_tags

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DriverOptionsModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DriverOptionsModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DriverOptionsModel):
            return True

        return self.to_dict() != other.to_dict()
