# coding: utf-8

"""
    Bumbal Client Api

    Bumbal API documentation  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: gerb@bumbal.eu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from bumbal.configuration import Configuration


class PackageLineOptionsModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'include_notes': 'bool',
        'include_tags': 'bool',
        'include_package_type_name': 'bool',
        'include_record_info': 'bool',
        'include_activity_ids': 'bool',
        'include_links': 'bool',
        'include_meta_data': 'bool',
        'include_files': 'bool',
        'include_capacities': 'bool',
        'include_filled_capacities': 'bool',
        'include_applied_capacities': 'bool',
        'include_package_lines_info': 'bool',
        'include_package_line_notes': 'bool',
        'include_package_line_tags': 'bool',
        'include_package_line_files_record_info': 'bool',
        'include_package_line_record_info': 'bool',
        'include_package_line_meta_data': 'bool',
        'include_package_line_files': 'bool',
        'include_package_line_files_meta_data': 'bool',
        'include_action_type_name': 'bool',
        'include_packagelines_for_whole_route_on_start_activity': 'bool'
    }

    attribute_map = {
        'include_notes': 'include_notes',
        'include_tags': 'include_tags',
        'include_package_type_name': 'include_package_type_name',
        'include_record_info': 'include_record_info',
        'include_activity_ids': 'include_activity_ids',
        'include_links': 'include_links',
        'include_meta_data': 'include_meta_data',
        'include_files': 'include_files',
        'include_capacities': 'include_capacities',
        'include_filled_capacities': 'include_filled_capacities',
        'include_applied_capacities': 'include_applied_capacities',
        'include_package_lines_info': 'include_package_lines_info',
        'include_package_line_notes': 'include_package_line_notes',
        'include_package_line_tags': 'include_package_line_tags',
        'include_package_line_files_record_info': 'include_package_line_files_record_info',
        'include_package_line_record_info': 'include_package_line_record_info',
        'include_package_line_meta_data': 'include_package_line_meta_data',
        'include_package_line_files': 'include_package_line_files',
        'include_package_line_files_meta_data': 'include_package_line_files_meta_data',
        'include_action_type_name': 'include_action_type_name',
        'include_packagelines_for_whole_route_on_start_activity': 'include_packagelines_for_whole_route_on_start_activity'
    }

    def __init__(self, include_notes=None, include_tags=None, include_package_type_name=None, include_record_info=None, include_activity_ids=None, include_links=None, include_meta_data=None, include_files=None, include_capacities=None, include_filled_capacities=None, include_applied_capacities=None, include_package_lines_info=None, include_package_line_notes=None, include_package_line_tags=None, include_package_line_files_record_info=None, include_package_line_record_info=None, include_package_line_meta_data=None, include_package_line_files=None, include_package_line_files_meta_data=None, include_action_type_name=None, include_packagelines_for_whole_route_on_start_activity=None, _configuration=None):  # noqa: E501
        """PackageLineOptionsModel - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._include_notes = None
        self._include_tags = None
        self._include_package_type_name = None
        self._include_record_info = None
        self._include_activity_ids = None
        self._include_links = None
        self._include_meta_data = None
        self._include_files = None
        self._include_capacities = None
        self._include_filled_capacities = None
        self._include_applied_capacities = None
        self._include_package_lines_info = None
        self._include_package_line_notes = None
        self._include_package_line_tags = None
        self._include_package_line_files_record_info = None
        self._include_package_line_record_info = None
        self._include_package_line_meta_data = None
        self._include_package_line_files = None
        self._include_package_line_files_meta_data = None
        self._include_action_type_name = None
        self._include_packagelines_for_whole_route_on_start_activity = None
        self.discriminator = None

        if include_notes is not None:
            self.include_notes = include_notes
        if include_tags is not None:
            self.include_tags = include_tags
        if include_package_type_name is not None:
            self.include_package_type_name = include_package_type_name
        if include_record_info is not None:
            self.include_record_info = include_record_info
        if include_activity_ids is not None:
            self.include_activity_ids = include_activity_ids
        if include_links is not None:
            self.include_links = include_links
        if include_meta_data is not None:
            self.include_meta_data = include_meta_data
        if include_files is not None:
            self.include_files = include_files
        if include_capacities is not None:
            self.include_capacities = include_capacities
        if include_filled_capacities is not None:
            self.include_filled_capacities = include_filled_capacities
        if include_applied_capacities is not None:
            self.include_applied_capacities = include_applied_capacities
        if include_package_lines_info is not None:
            self.include_package_lines_info = include_package_lines_info
        if include_package_line_notes is not None:
            self.include_package_line_notes = include_package_line_notes
        if include_package_line_tags is not None:
            self.include_package_line_tags = include_package_line_tags
        if include_package_line_files_record_info is not None:
            self.include_package_line_files_record_info = include_package_line_files_record_info
        if include_package_line_record_info is not None:
            self.include_package_line_record_info = include_package_line_record_info
        if include_package_line_meta_data is not None:
            self.include_package_line_meta_data = include_package_line_meta_data
        if include_package_line_files is not None:
            self.include_package_line_files = include_package_line_files
        if include_package_line_files_meta_data is not None:
            self.include_package_line_files_meta_data = include_package_line_files_meta_data
        if include_action_type_name is not None:
            self.include_action_type_name = include_action_type_name
        if include_packagelines_for_whole_route_on_start_activity is not None:
            self.include_packagelines_for_whole_route_on_start_activity = include_packagelines_for_whole_route_on_start_activity

    @property
    def include_notes(self):
        """Gets the include_notes of this PackageLineOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_notes of this PackageLineOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_notes

    @include_notes.setter
    def include_notes(self, include_notes):
        """Sets the include_notes of this PackageLineOptionsModel.

          # noqa: E501

        :param include_notes: The include_notes of this PackageLineOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_notes = include_notes

    @property
    def include_tags(self):
        """Gets the include_tags of this PackageLineOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_tags of this PackageLineOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_tags

    @include_tags.setter
    def include_tags(self, include_tags):
        """Sets the include_tags of this PackageLineOptionsModel.

          # noqa: E501

        :param include_tags: The include_tags of this PackageLineOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_tags = include_tags

    @property
    def include_package_type_name(self):
        """Gets the include_package_type_name of this PackageLineOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_package_type_name of this PackageLineOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_package_type_name

    @include_package_type_name.setter
    def include_package_type_name(self, include_package_type_name):
        """Sets the include_package_type_name of this PackageLineOptionsModel.

          # noqa: E501

        :param include_package_type_name: The include_package_type_name of this PackageLineOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_package_type_name = include_package_type_name

    @property
    def include_record_info(self):
        """Gets the include_record_info of this PackageLineOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_record_info of this PackageLineOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_record_info

    @include_record_info.setter
    def include_record_info(self, include_record_info):
        """Sets the include_record_info of this PackageLineOptionsModel.

          # noqa: E501

        :param include_record_info: The include_record_info of this PackageLineOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_record_info = include_record_info

    @property
    def include_activity_ids(self):
        """Gets the include_activity_ids of this PackageLineOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_activity_ids of this PackageLineOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_activity_ids

    @include_activity_ids.setter
    def include_activity_ids(self, include_activity_ids):
        """Sets the include_activity_ids of this PackageLineOptionsModel.

          # noqa: E501

        :param include_activity_ids: The include_activity_ids of this PackageLineOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_activity_ids = include_activity_ids

    @property
    def include_links(self):
        """Gets the include_links of this PackageLineOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_links of this PackageLineOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_links

    @include_links.setter
    def include_links(self, include_links):
        """Sets the include_links of this PackageLineOptionsModel.

          # noqa: E501

        :param include_links: The include_links of this PackageLineOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_links = include_links

    @property
    def include_meta_data(self):
        """Gets the include_meta_data of this PackageLineOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_meta_data of this PackageLineOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_meta_data

    @include_meta_data.setter
    def include_meta_data(self, include_meta_data):
        """Sets the include_meta_data of this PackageLineOptionsModel.

          # noqa: E501

        :param include_meta_data: The include_meta_data of this PackageLineOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_meta_data = include_meta_data

    @property
    def include_files(self):
        """Gets the include_files of this PackageLineOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_files of this PackageLineOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_files

    @include_files.setter
    def include_files(self, include_files):
        """Sets the include_files of this PackageLineOptionsModel.

          # noqa: E501

        :param include_files: The include_files of this PackageLineOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_files = include_files

    @property
    def include_capacities(self):
        """Gets the include_capacities of this PackageLineOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_capacities of this PackageLineOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_capacities

    @include_capacities.setter
    def include_capacities(self, include_capacities):
        """Sets the include_capacities of this PackageLineOptionsModel.

          # noqa: E501

        :param include_capacities: The include_capacities of this PackageLineOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_capacities = include_capacities

    @property
    def include_filled_capacities(self):
        """Gets the include_filled_capacities of this PackageLineOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_filled_capacities of this PackageLineOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_filled_capacities

    @include_filled_capacities.setter
    def include_filled_capacities(self, include_filled_capacities):
        """Sets the include_filled_capacities of this PackageLineOptionsModel.

          # noqa: E501

        :param include_filled_capacities: The include_filled_capacities of this PackageLineOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_filled_capacities = include_filled_capacities

    @property
    def include_applied_capacities(self):
        """Gets the include_applied_capacities of this PackageLineOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_applied_capacities of this PackageLineOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_applied_capacities

    @include_applied_capacities.setter
    def include_applied_capacities(self, include_applied_capacities):
        """Sets the include_applied_capacities of this PackageLineOptionsModel.

          # noqa: E501

        :param include_applied_capacities: The include_applied_capacities of this PackageLineOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_applied_capacities = include_applied_capacities

    @property
    def include_package_lines_info(self):
        """Gets the include_package_lines_info of this PackageLineOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_package_lines_info of this PackageLineOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_package_lines_info

    @include_package_lines_info.setter
    def include_package_lines_info(self, include_package_lines_info):
        """Sets the include_package_lines_info of this PackageLineOptionsModel.

          # noqa: E501

        :param include_package_lines_info: The include_package_lines_info of this PackageLineOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_package_lines_info = include_package_lines_info

    @property
    def include_package_line_notes(self):
        """Gets the include_package_line_notes of this PackageLineOptionsModel.  # noqa: E501

        Deprecated! use include_notes and include_package_lines  # noqa: E501

        :return: The include_package_line_notes of this PackageLineOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_package_line_notes

    @include_package_line_notes.setter
    def include_package_line_notes(self, include_package_line_notes):
        """Sets the include_package_line_notes of this PackageLineOptionsModel.

        Deprecated! use include_notes and include_package_lines  # noqa: E501

        :param include_package_line_notes: The include_package_line_notes of this PackageLineOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_package_line_notes = include_package_line_notes

    @property
    def include_package_line_tags(self):
        """Gets the include_package_line_tags of this PackageLineOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_package_line_tags of this PackageLineOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_package_line_tags

    @include_package_line_tags.setter
    def include_package_line_tags(self, include_package_line_tags):
        """Sets the include_package_line_tags of this PackageLineOptionsModel.

          # noqa: E501

        :param include_package_line_tags: The include_package_line_tags of this PackageLineOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_package_line_tags = include_package_line_tags

    @property
    def include_package_line_files_record_info(self):
        """Gets the include_package_line_files_record_info of this PackageLineOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_package_line_files_record_info of this PackageLineOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_package_line_files_record_info

    @include_package_line_files_record_info.setter
    def include_package_line_files_record_info(self, include_package_line_files_record_info):
        """Sets the include_package_line_files_record_info of this PackageLineOptionsModel.

          # noqa: E501

        :param include_package_line_files_record_info: The include_package_line_files_record_info of this PackageLineOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_package_line_files_record_info = include_package_line_files_record_info

    @property
    def include_package_line_record_info(self):
        """Gets the include_package_line_record_info of this PackageLineOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_package_line_record_info of this PackageLineOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_package_line_record_info

    @include_package_line_record_info.setter
    def include_package_line_record_info(self, include_package_line_record_info):
        """Sets the include_package_line_record_info of this PackageLineOptionsModel.

          # noqa: E501

        :param include_package_line_record_info: The include_package_line_record_info of this PackageLineOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_package_line_record_info = include_package_line_record_info

    @property
    def include_package_line_meta_data(self):
        """Gets the include_package_line_meta_data of this PackageLineOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_package_line_meta_data of this PackageLineOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_package_line_meta_data

    @include_package_line_meta_data.setter
    def include_package_line_meta_data(self, include_package_line_meta_data):
        """Sets the include_package_line_meta_data of this PackageLineOptionsModel.

          # noqa: E501

        :param include_package_line_meta_data: The include_package_line_meta_data of this PackageLineOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_package_line_meta_data = include_package_line_meta_data

    @property
    def include_package_line_files(self):
        """Gets the include_package_line_files of this PackageLineOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_package_line_files of this PackageLineOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_package_line_files

    @include_package_line_files.setter
    def include_package_line_files(self, include_package_line_files):
        """Sets the include_package_line_files of this PackageLineOptionsModel.

          # noqa: E501

        :param include_package_line_files: The include_package_line_files of this PackageLineOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_package_line_files = include_package_line_files

    @property
    def include_package_line_files_meta_data(self):
        """Gets the include_package_line_files_meta_data of this PackageLineOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_package_line_files_meta_data of this PackageLineOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_package_line_files_meta_data

    @include_package_line_files_meta_data.setter
    def include_package_line_files_meta_data(self, include_package_line_files_meta_data):
        """Sets the include_package_line_files_meta_data of this PackageLineOptionsModel.

          # noqa: E501

        :param include_package_line_files_meta_data: The include_package_line_files_meta_data of this PackageLineOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_package_line_files_meta_data = include_package_line_files_meta_data

    @property
    def include_action_type_name(self):
        """Gets the include_action_type_name of this PackageLineOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_action_type_name of this PackageLineOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_action_type_name

    @include_action_type_name.setter
    def include_action_type_name(self, include_action_type_name):
        """Sets the include_action_type_name of this PackageLineOptionsModel.

          # noqa: E501

        :param include_action_type_name: The include_action_type_name of this PackageLineOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_action_type_name = include_action_type_name

    @property
    def include_packagelines_for_whole_route_on_start_activity(self):
        """Gets the include_packagelines_for_whole_route_on_start_activity of this PackageLineOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_packagelines_for_whole_route_on_start_activity of this PackageLineOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_packagelines_for_whole_route_on_start_activity

    @include_packagelines_for_whole_route_on_start_activity.setter
    def include_packagelines_for_whole_route_on_start_activity(self, include_packagelines_for_whole_route_on_start_activity):
        """Sets the include_packagelines_for_whole_route_on_start_activity of this PackageLineOptionsModel.

          # noqa: E501

        :param include_packagelines_for_whole_route_on_start_activity: The include_packagelines_for_whole_route_on_start_activity of this PackageLineOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_packagelines_for_whole_route_on_start_activity = include_packagelines_for_whole_route_on_start_activity

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PackageLineOptionsModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PackageLineOptionsModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PackageLineOptionsModel):
            return True

        return self.to_dict() != other.to_dict()
