# coding: utf-8

"""
    Bumbal Client Api

    Bumbal API documentation  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: gerb@bumbal.eu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from bumbal.configuration import Configuration


class QuestionnaireTemplateQuestionModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'active': 'bool',
        'questionnaire_template_id': 'int',
        'question_type_id': 'int',
        'question_type_name': 'str',
        'order': 'int',
        'options': 'list[QuestionnaireTemplateQuestionOptionModel]',
        'texts': 'list[QuestionnaireTemplateQuestionTextModel]'
    }

    attribute_map = {
        'id': 'id',
        'active': 'active',
        'questionnaire_template_id': 'questionnaire_template_id',
        'question_type_id': 'question_type_id',
        'question_type_name': 'question_type_name',
        'order': 'order',
        'options': 'options',
        'texts': 'texts'
    }

    def __init__(self, id=None, active=None, questionnaire_template_id=None, question_type_id=None, question_type_name=None, order=None, options=None, texts=None, _configuration=None):  # noqa: E501
        """QuestionnaireTemplateQuestionModel - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._active = None
        self._questionnaire_template_id = None
        self._question_type_id = None
        self._question_type_name = None
        self._order = None
        self._options = None
        self._texts = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if active is not None:
            self.active = active
        if questionnaire_template_id is not None:
            self.questionnaire_template_id = questionnaire_template_id
        if question_type_id is not None:
            self.question_type_id = question_type_id
        if question_type_name is not None:
            self.question_type_name = question_type_name
        if order is not None:
            self.order = order
        if options is not None:
            self.options = options
        if texts is not None:
            self.texts = texts

    @property
    def id(self):
        """Gets the id of this QuestionnaireTemplateQuestionModel.  # noqa: E501

        Unique Identifier  # noqa: E501

        :return: The id of this QuestionnaireTemplateQuestionModel.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this QuestionnaireTemplateQuestionModel.

        Unique Identifier  # noqa: E501

        :param id: The id of this QuestionnaireTemplateQuestionModel.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def active(self):
        """Gets the active of this QuestionnaireTemplateQuestionModel.  # noqa: E501

        if active=0: note has been removed and is no longer visible in any bumbal interface  # noqa: E501

        :return: The active of this QuestionnaireTemplateQuestionModel.  # noqa: E501
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this QuestionnaireTemplateQuestionModel.

        if active=0: note has been removed and is no longer visible in any bumbal interface  # noqa: E501

        :param active: The active of this QuestionnaireTemplateQuestionModel.  # noqa: E501
        :type: bool
        """

        self._active = active

    @property
    def questionnaire_template_id(self):
        """Gets the questionnaire_template_id of this QuestionnaireTemplateQuestionModel.  # noqa: E501

        Questionnaire template id  # noqa: E501

        :return: The questionnaire_template_id of this QuestionnaireTemplateQuestionModel.  # noqa: E501
        :rtype: int
        """
        return self._questionnaire_template_id

    @questionnaire_template_id.setter
    def questionnaire_template_id(self, questionnaire_template_id):
        """Sets the questionnaire_template_id of this QuestionnaireTemplateQuestionModel.

        Questionnaire template id  # noqa: E501

        :param questionnaire_template_id: The questionnaire_template_id of this QuestionnaireTemplateQuestionModel.  # noqa: E501
        :type: int
        """

        self._questionnaire_template_id = questionnaire_template_id

    @property
    def question_type_id(self):
        """Gets the question_type_id of this QuestionnaireTemplateQuestionModel.  # noqa: E501

        Question type id  # noqa: E501

        :return: The question_type_id of this QuestionnaireTemplateQuestionModel.  # noqa: E501
        :rtype: int
        """
        return self._question_type_id

    @question_type_id.setter
    def question_type_id(self, question_type_id):
        """Sets the question_type_id of this QuestionnaireTemplateQuestionModel.

        Question type id  # noqa: E501

        :param question_type_id: The question_type_id of this QuestionnaireTemplateQuestionModel.  # noqa: E501
        :type: int
        """

        self._question_type_id = question_type_id

    @property
    def question_type_name(self):
        """Gets the question_type_name of this QuestionnaireTemplateQuestionModel.  # noqa: E501

        Question type name  # noqa: E501

        :return: The question_type_name of this QuestionnaireTemplateQuestionModel.  # noqa: E501
        :rtype: str
        """
        return self._question_type_name

    @question_type_name.setter
    def question_type_name(self, question_type_name):
        """Sets the question_type_name of this QuestionnaireTemplateQuestionModel.

        Question type name  # noqa: E501

        :param question_type_name: The question_type_name of this QuestionnaireTemplateQuestionModel.  # noqa: E501
        :type: str
        """

        self._question_type_name = question_type_name

    @property
    def order(self):
        """Gets the order of this QuestionnaireTemplateQuestionModel.  # noqa: E501

        Order  # noqa: E501

        :return: The order of this QuestionnaireTemplateQuestionModel.  # noqa: E501
        :rtype: int
        """
        return self._order

    @order.setter
    def order(self, order):
        """Sets the order of this QuestionnaireTemplateQuestionModel.

        Order  # noqa: E501

        :param order: The order of this QuestionnaireTemplateQuestionModel.  # noqa: E501
        :type: int
        """

        self._order = order

    @property
    def options(self):
        """Gets the options of this QuestionnaireTemplateQuestionModel.  # noqa: E501

          # noqa: E501

        :return: The options of this QuestionnaireTemplateQuestionModel.  # noqa: E501
        :rtype: list[QuestionnaireTemplateQuestionOptionModel]
        """
        return self._options

    @options.setter
    def options(self, options):
        """Sets the options of this QuestionnaireTemplateQuestionModel.

          # noqa: E501

        :param options: The options of this QuestionnaireTemplateQuestionModel.  # noqa: E501
        :type: list[QuestionnaireTemplateQuestionOptionModel]
        """

        self._options = options

    @property
    def texts(self):
        """Gets the texts of this QuestionnaireTemplateQuestionModel.  # noqa: E501

          # noqa: E501

        :return: The texts of this QuestionnaireTemplateQuestionModel.  # noqa: E501
        :rtype: list[QuestionnaireTemplateQuestionTextModel]
        """
        return self._texts

    @texts.setter
    def texts(self, texts):
        """Sets the texts of this QuestionnaireTemplateQuestionModel.

          # noqa: E501

        :param texts: The texts of this QuestionnaireTemplateQuestionModel.  # noqa: E501
        :type: list[QuestionnaireTemplateQuestionTextModel]
        """

        self._texts = texts

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(QuestionnaireTemplateQuestionModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QuestionnaireTemplateQuestionModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, QuestionnaireTemplateQuestionModel):
            return True

        return self.to_dict() != other.to_dict()
