# coding: utf-8

"""
    Bumbal Client Api

    Bumbal API documentation  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: gerb@bumbal.eu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from bumbal.configuration import Configuration


class UsersOptionsModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'include_addresses': 'bool',
        'include_user_meta_data': 'bool',
        'include_user_tags': 'bool',
        'include_party_name': 'bool',
        'include_pause': 'bool',
        'include_zones': 'bool',
        'include_driver_unavailabilities': 'bool',
        'include_links': 'bool'
    }

    attribute_map = {
        'include_addresses': 'include_addresses',
        'include_user_meta_data': 'include_user_meta_data',
        'include_user_tags': 'include_user_tags',
        'include_party_name': 'include_party_name',
        'include_pause': 'include_pause',
        'include_zones': 'include_zones',
        'include_driver_unavailabilities': 'include_driver_unavailabilities',
        'include_links': 'include_links'
    }

    def __init__(self, include_addresses=None, include_user_meta_data=None, include_user_tags=None, include_party_name=None, include_pause=None, include_zones=None, include_driver_unavailabilities=None, include_links=None, _configuration=None):  # noqa: E501
        """UsersOptionsModel - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._include_addresses = None
        self._include_user_meta_data = None
        self._include_user_tags = None
        self._include_party_name = None
        self._include_pause = None
        self._include_zones = None
        self._include_driver_unavailabilities = None
        self._include_links = None
        self.discriminator = None

        if include_addresses is not None:
            self.include_addresses = include_addresses
        if include_user_meta_data is not None:
            self.include_user_meta_data = include_user_meta_data
        if include_user_tags is not None:
            self.include_user_tags = include_user_tags
        if include_party_name is not None:
            self.include_party_name = include_party_name
        if include_pause is not None:
            self.include_pause = include_pause
        if include_zones is not None:
            self.include_zones = include_zones
        if include_driver_unavailabilities is not None:
            self.include_driver_unavailabilities = include_driver_unavailabilities
        if include_links is not None:
            self.include_links = include_links

    @property
    def include_addresses(self):
        """Gets the include_addresses of this UsersOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_addresses of this UsersOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_addresses

    @include_addresses.setter
    def include_addresses(self, include_addresses):
        """Sets the include_addresses of this UsersOptionsModel.

          # noqa: E501

        :param include_addresses: The include_addresses of this UsersOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_addresses = include_addresses

    @property
    def include_user_meta_data(self):
        """Gets the include_user_meta_data of this UsersOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_user_meta_data of this UsersOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_user_meta_data

    @include_user_meta_data.setter
    def include_user_meta_data(self, include_user_meta_data):
        """Sets the include_user_meta_data of this UsersOptionsModel.

          # noqa: E501

        :param include_user_meta_data: The include_user_meta_data of this UsersOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_user_meta_data = include_user_meta_data

    @property
    def include_user_tags(self):
        """Gets the include_user_tags of this UsersOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_user_tags of this UsersOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_user_tags

    @include_user_tags.setter
    def include_user_tags(self, include_user_tags):
        """Sets the include_user_tags of this UsersOptionsModel.

          # noqa: E501

        :param include_user_tags: The include_user_tags of this UsersOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_user_tags = include_user_tags

    @property
    def include_party_name(self):
        """Gets the include_party_name of this UsersOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_party_name of this UsersOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_party_name

    @include_party_name.setter
    def include_party_name(self, include_party_name):
        """Sets the include_party_name of this UsersOptionsModel.

          # noqa: E501

        :param include_party_name: The include_party_name of this UsersOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_party_name = include_party_name

    @property
    def include_pause(self):
        """Gets the include_pause of this UsersOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_pause of this UsersOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_pause

    @include_pause.setter
    def include_pause(self, include_pause):
        """Sets the include_pause of this UsersOptionsModel.

          # noqa: E501

        :param include_pause: The include_pause of this UsersOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_pause = include_pause

    @property
    def include_zones(self):
        """Gets the include_zones of this UsersOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_zones of this UsersOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_zones

    @include_zones.setter
    def include_zones(self, include_zones):
        """Sets the include_zones of this UsersOptionsModel.

          # noqa: E501

        :param include_zones: The include_zones of this UsersOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_zones = include_zones

    @property
    def include_driver_unavailabilities(self):
        """Gets the include_driver_unavailabilities of this UsersOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_driver_unavailabilities of this UsersOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_driver_unavailabilities

    @include_driver_unavailabilities.setter
    def include_driver_unavailabilities(self, include_driver_unavailabilities):
        """Sets the include_driver_unavailabilities of this UsersOptionsModel.

          # noqa: E501

        :param include_driver_unavailabilities: The include_driver_unavailabilities of this UsersOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_driver_unavailabilities = include_driver_unavailabilities

    @property
    def include_links(self):
        """Gets the include_links of this UsersOptionsModel.  # noqa: E501

          # noqa: E501

        :return: The include_links of this UsersOptionsModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_links

    @include_links.setter
    def include_links(self, include_links):
        """Sets the include_links of this UsersOptionsModel.

          # noqa: E501

        :param include_links: The include_links of this UsersOptionsModel.  # noqa: E501
        :type: bool
        """

        self._include_links = include_links

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UsersOptionsModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UsersOptionsModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UsersOptionsModel):
            return True

        return self.to_dict() != other.to_dict()
