# coding: utf-8

"""
    Bumbal Client Api

    Bumbal API documentation  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: gerb@bumbal.eu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from bumbal.api_client import ApiClient


class CommunicationApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def retrieve_activity_communication(self, activity_id, **kwargs):  # noqa: E501
        """Retrieve Activity  # noqa: E501

        Retrieve Activity from Communication  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.retrieve_activity_communication(activity_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int activity_id: ActivityId (required)
        :return: ApiResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.retrieve_activity_communication_with_http_info(activity_id, **kwargs)  # noqa: E501
        else:
            (data) = self.retrieve_activity_communication_with_http_info(activity_id, **kwargs)  # noqa: E501
            return data

    def retrieve_activity_communication_with_http_info(self, activity_id, **kwargs):  # noqa: E501
        """Retrieve Activity  # noqa: E501

        Retrieve Activity from Communication  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.retrieve_activity_communication_with_http_info(activity_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int activity_id: ActivityId (required)
        :return: ApiResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['activity_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method retrieve_activity_communication" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'activity_id' is set
        if self.api_client.client_side_validation and ('activity_id' not in params or
                                                       params['activity_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `activity_id` when calling `retrieve_activity_communication`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'activity_id' in params:
            query_params.append(('activityId', params['activity_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/xml', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key', 'jwt']  # noqa: E501

        return self.api_client.call_api(
            '/communication/retrieve-activity', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ApiResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def trigger_message_communication(self, activity_id, message_type, check_preference, **kwargs):  # noqa: E501
        """Trigger Message to Communication  # noqa: E501

        Trigger Message to Communication  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.trigger_message_communication(activity_id, message_type, check_preference, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int activity_id: ActivityId (required)
        :param str message_type: MessageType (required)
        :param bool check_preference: checkPreference (required)
        :return: ApiResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.trigger_message_communication_with_http_info(activity_id, message_type, check_preference, **kwargs)  # noqa: E501
        else:
            (data) = self.trigger_message_communication_with_http_info(activity_id, message_type, check_preference, **kwargs)  # noqa: E501
            return data

    def trigger_message_communication_with_http_info(self, activity_id, message_type, check_preference, **kwargs):  # noqa: E501
        """Trigger Message to Communication  # noqa: E501

        Trigger Message to Communication  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.trigger_message_communication_with_http_info(activity_id, message_type, check_preference, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int activity_id: ActivityId (required)
        :param str message_type: MessageType (required)
        :param bool check_preference: checkPreference (required)
        :return: ApiResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['activity_id', 'message_type', 'check_preference']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method trigger_message_communication" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'activity_id' is set
        if self.api_client.client_side_validation and ('activity_id' not in params or
                                                       params['activity_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `activity_id` when calling `trigger_message_communication`")  # noqa: E501
        # verify the required parameter 'message_type' is set
        if self.api_client.client_side_validation and ('message_type' not in params or
                                                       params['message_type'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `message_type` when calling `trigger_message_communication`")  # noqa: E501
        # verify the required parameter 'check_preference' is set
        if self.api_client.client_side_validation and ('check_preference' not in params or
                                                       params['check_preference'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `check_preference` when calling `trigger_message_communication`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'activity_id' in params:
            form_params.append(('activityId', params['activity_id']))  # noqa: E501
        if 'message_type' in params:
            form_params.append(('messageType', params['message_type']))  # noqa: E501
        if 'check_preference' in params:
            form_params.append(('checkPreference', params['check_preference']))  # noqa: E501

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/xml', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key', 'jwt']  # noqa: E501

        return self.api_client.call_api(
            '/communication/trigger-message', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ApiResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
