# coding: utf-8

"""
    Bumbal Client Api

    Bumbal API documentation  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: gerb@bumbal.eu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from bumbal.api_client import ApiClient


class NoteApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def delete_note(self, note_id, **kwargs):  # noqa: E501
        """Delete an note  # noqa: E501

        Delete an note  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_note(note_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int note_id: ID of the note to delete (required)
        :return: ApiResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_note_with_http_info(note_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_note_with_http_info(note_id, **kwargs)  # noqa: E501
            return data

    def delete_note_with_http_info(self, note_id, **kwargs):  # noqa: E501
        """Delete an note  # noqa: E501

        Delete an note  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_note_with_http_info(note_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int note_id: ID of the note to delete (required)
        :return: ApiResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['note_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_note" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'note_id' is set
        if self.api_client.client_side_validation and ('note_id' not in params or
                                                       params['note_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `note_id` when calling `delete_note`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'note_id' in params:
            path_params['noteId'] = params['note_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key', 'jwt']  # noqa: E501

        return self.api_client.call_api(
            '/note/{noteId}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ApiResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def retrieve_list_note(self, arguments, **kwargs):  # noqa: E501
        """Retrieve List of Notes  # noqa: E501

        Retrieve List of Notes  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.retrieve_list_note(arguments, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param NoteRetrieveListArguments arguments: Note RetrieveList Arguments (required)
        :return: list[NoteModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.retrieve_list_note_with_http_info(arguments, **kwargs)  # noqa: E501
        else:
            (data) = self.retrieve_list_note_with_http_info(arguments, **kwargs)  # noqa: E501
            return data

    def retrieve_list_note_with_http_info(self, arguments, **kwargs):  # noqa: E501
        """Retrieve List of Notes  # noqa: E501

        Retrieve List of Notes  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.retrieve_list_note_with_http_info(arguments, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param NoteRetrieveListArguments arguments: Note RetrieveList Arguments (required)
        :return: list[NoteModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['arguments']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method retrieve_list_note" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'arguments' is set
        if self.api_client.client_side_validation and ('arguments' not in params or
                                                       params['arguments'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `arguments` when calling `retrieve_list_note`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'arguments' in params:
            body_params = params['arguments']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key', 'jwt']  # noqa: E501

        return self.api_client.call_api(
            '/note', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[NoteModel]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def retrieve_note(self, note_id, include_note_tags, include_note_tag_type_link_ids, include_note_object_link_ids, include_updated_by, **kwargs):  # noqa: E501
        """Find note by ID  # noqa: E501

        Returns a single note  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.retrieve_note(note_id, include_note_tags, include_note_tag_type_link_ids, include_note_object_link_ids, include_updated_by, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int note_id: ID of note to return (required)
        :param bool include_note_tags: a list of tags bound to note (required)
        :param bool include_note_tag_type_link_ids: link ids of the tag types (required)
        :param bool include_note_object_link_ids: Include teh link ids bound to teh object where teh note belongs to (required)
        :param bool include_updated_by: include updated_by_name (required)
        :return: NoteModel
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.retrieve_note_with_http_info(note_id, include_note_tags, include_note_tag_type_link_ids, include_note_object_link_ids, include_updated_by, **kwargs)  # noqa: E501
        else:
            (data) = self.retrieve_note_with_http_info(note_id, include_note_tags, include_note_tag_type_link_ids, include_note_object_link_ids, include_updated_by, **kwargs)  # noqa: E501
            return data

    def retrieve_note_with_http_info(self, note_id, include_note_tags, include_note_tag_type_link_ids, include_note_object_link_ids, include_updated_by, **kwargs):  # noqa: E501
        """Find note by ID  # noqa: E501

        Returns a single note  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.retrieve_note_with_http_info(note_id, include_note_tags, include_note_tag_type_link_ids, include_note_object_link_ids, include_updated_by, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int note_id: ID of note to return (required)
        :param bool include_note_tags: a list of tags bound to note (required)
        :param bool include_note_tag_type_link_ids: link ids of the tag types (required)
        :param bool include_note_object_link_ids: Include teh link ids bound to teh object where teh note belongs to (required)
        :param bool include_updated_by: include updated_by_name (required)
        :return: NoteModel
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['note_id', 'include_note_tags', 'include_note_tag_type_link_ids', 'include_note_object_link_ids', 'include_updated_by']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method retrieve_note" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'note_id' is set
        if self.api_client.client_side_validation and ('note_id' not in params or
                                                       params['note_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `note_id` when calling `retrieve_note`")  # noqa: E501
        # verify the required parameter 'include_note_tags' is set
        if self.api_client.client_side_validation and ('include_note_tags' not in params or
                                                       params['include_note_tags'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `include_note_tags` when calling `retrieve_note`")  # noqa: E501
        # verify the required parameter 'include_note_tag_type_link_ids' is set
        if self.api_client.client_side_validation and ('include_note_tag_type_link_ids' not in params or
                                                       params['include_note_tag_type_link_ids'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `include_note_tag_type_link_ids` when calling `retrieve_note`")  # noqa: E501
        # verify the required parameter 'include_note_object_link_ids' is set
        if self.api_client.client_side_validation and ('include_note_object_link_ids' not in params or
                                                       params['include_note_object_link_ids'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `include_note_object_link_ids` when calling `retrieve_note`")  # noqa: E501
        # verify the required parameter 'include_updated_by' is set
        if self.api_client.client_side_validation and ('include_updated_by' not in params or
                                                       params['include_updated_by'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `include_updated_by` when calling `retrieve_note`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'note_id' in params:
            path_params['noteId'] = params['note_id']  # noqa: E501

        query_params = []
        if 'include_note_tags' in params:
            query_params.append(('include_note_tags', params['include_note_tags']))  # noqa: E501
        if 'include_note_tag_type_link_ids' in params:
            query_params.append(('include_note_tag_type_link_ids', params['include_note_tag_type_link_ids']))  # noqa: E501
        if 'include_note_object_link_ids' in params:
            query_params.append(('include_note_object_link_ids', params['include_note_object_link_ids']))  # noqa: E501
        if 'include_updated_by' in params:
            query_params.append(('include_updated_by', params['include_updated_by']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key', 'jwt']  # noqa: E501

        return self.api_client.call_api(
            '/note/{noteId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='NoteModel',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def set_note(self, **kwargs):  # noqa: E501
        """Set (create or update) a note  # noqa: E501

        Set (create or update) a note. If id or links are set in the data, and a corresponding note is found in Bumbal, an update will be performed.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.set_note(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param NoteModel body: Note object
        :return: ApiResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.set_note_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.set_note_with_http_info(**kwargs)  # noqa: E501
            return data

    def set_note_with_http_info(self, **kwargs):  # noqa: E501
        """Set (create or update) a note  # noqa: E501

        Set (create or update) a note. If id or links are set in the data, and a corresponding note is found in Bumbal, an update will be performed.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.set_note_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param NoteModel body: Note object
        :return: ApiResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method set_note" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key', 'jwt']  # noqa: E501

        return self.api_client.call_api(
            '/note/set', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ApiResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
