# coding: utf-8

"""
    Bumbal Client Api

    Bumbal API documentation  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: gerb@bumbal.eu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from bumbal.api_client import ApiClient


class QuestionnaireTemplateApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def create_questionnaire_template(self, **kwargs):  # noqa: E501
        """Add a new QuestionnaireTemplate  # noqa: E501

        Add a new QuestionnaireTemplate  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_questionnaire_template(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param QuestionnaireTemplateModel body: QuestionnaireTemplate object that needs to be created
        :return: ApiResponse33
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_questionnaire_template_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.create_questionnaire_template_with_http_info(**kwargs)  # noqa: E501
            return data

    def create_questionnaire_template_with_http_info(self, **kwargs):  # noqa: E501
        """Add a new QuestionnaireTemplate  # noqa: E501

        Add a new QuestionnaireTemplate  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_questionnaire_template_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param QuestionnaireTemplateModel body: QuestionnaireTemplate object that needs to be created
        :return: ApiResponse33
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_questionnaire_template" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key', 'jwt']  # noqa: E501

        return self.api_client.call_api(
            '/questionnaire-template', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ApiResponse33',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_questionnaire_template(self, questionnaire_template_id, **kwargs):  # noqa: E501
        """Delete an QuestionnaireTemplate entry  # noqa: E501

        Delete an QuestionnaireTemplate entry  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_questionnaire_template(questionnaire_template_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int questionnaire_template_id: ID of QuestionnaireTemplate to delete (required)
        :return: ApiResponse31
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_questionnaire_template_with_http_info(questionnaire_template_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_questionnaire_template_with_http_info(questionnaire_template_id, **kwargs)  # noqa: E501
            return data

    def delete_questionnaire_template_with_http_info(self, questionnaire_template_id, **kwargs):  # noqa: E501
        """Delete an QuestionnaireTemplate entry  # noqa: E501

        Delete an QuestionnaireTemplate entry  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_questionnaire_template_with_http_info(questionnaire_template_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int questionnaire_template_id: ID of QuestionnaireTemplate to delete (required)
        :return: ApiResponse31
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['questionnaire_template_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_questionnaire_template" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'questionnaire_template_id' is set
        if self.api_client.client_side_validation and ('questionnaire_template_id' not in params or
                                                       params['questionnaire_template_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `questionnaire_template_id` when calling `delete_questionnaire_template`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'questionnaire_template_id' in params:
            path_params['questionnaire-templateId'] = params['questionnaire_template_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key', 'jwt']  # noqa: E501

        return self.api_client.call_api(
            '/questionnaire-template/{questionnaire-templateId}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ApiResponse31',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def retrieve_list_questionnaire_template(self, arguments, **kwargs):  # noqa: E501
        """Retrieve List of QuestionnaireTemplate  # noqa: E501

        Retrieve List of QuestionnaireTemplate  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.retrieve_list_questionnaire_template(arguments, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param QuestionnaireTemplateRetrieveListArguments arguments: QuestionnaireTemplate RetrieveList Arguments (required)
        :return: QuestionnaireTemplateListResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.retrieve_list_questionnaire_template_with_http_info(arguments, **kwargs)  # noqa: E501
        else:
            (data) = self.retrieve_list_questionnaire_template_with_http_info(arguments, **kwargs)  # noqa: E501
            return data

    def retrieve_list_questionnaire_template_with_http_info(self, arguments, **kwargs):  # noqa: E501
        """Retrieve List of QuestionnaireTemplate  # noqa: E501

        Retrieve List of QuestionnaireTemplate  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.retrieve_list_questionnaire_template_with_http_info(arguments, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param QuestionnaireTemplateRetrieveListArguments arguments: QuestionnaireTemplate RetrieveList Arguments (required)
        :return: QuestionnaireTemplateListResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['arguments']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method retrieve_list_questionnaire_template" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'arguments' is set
        if self.api_client.client_side_validation and ('arguments' not in params or
                                                       params['arguments'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `arguments` when calling `retrieve_list_questionnaire_template`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'arguments' in params:
            body_params = params['arguments']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key', 'jwt']  # noqa: E501

        return self.api_client.call_api(
            '/questionnaire-template', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='QuestionnaireTemplateListResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def retrieve_questionnaire_template(self, questionnaire_template_id, **kwargs):  # noqa: E501
        """Retrieve a QuestionnaireTemplate  # noqa: E501

        Retrieve an QuestionnaireTemplate  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.retrieve_questionnaire_template(questionnaire_template_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int questionnaire_template_id: ID of QuestionnaireTemplate to retrieve (required)
        :return: QuestionnaireTemplateModel
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.retrieve_questionnaire_template_with_http_info(questionnaire_template_id, **kwargs)  # noqa: E501
        else:
            (data) = self.retrieve_questionnaire_template_with_http_info(questionnaire_template_id, **kwargs)  # noqa: E501
            return data

    def retrieve_questionnaire_template_with_http_info(self, questionnaire_template_id, **kwargs):  # noqa: E501
        """Retrieve a QuestionnaireTemplate  # noqa: E501

        Retrieve an QuestionnaireTemplate  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.retrieve_questionnaire_template_with_http_info(questionnaire_template_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int questionnaire_template_id: ID of QuestionnaireTemplate to retrieve (required)
        :return: QuestionnaireTemplateModel
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['questionnaire_template_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method retrieve_questionnaire_template" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'questionnaire_template_id' is set
        if self.api_client.client_side_validation and ('questionnaire_template_id' not in params or
                                                       params['questionnaire_template_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `questionnaire_template_id` when calling `retrieve_questionnaire_template`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'questionnaire_template_id' in params:
            path_params['questionnaire-templateId'] = params['questionnaire_template_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key', 'jwt']  # noqa: E501

        return self.api_client.call_api(
            '/questionnaire-template/{questionnaire-templateId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='QuestionnaireTemplateModel',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def set_questionnaire_template(self, **kwargs):  # noqa: E501
        """Set (create or update) a QuestionnaireTemplate  # noqa: E501

        Set (create or update) a d=QuestionnaireTemplate. If id or links are set in the data, and a corresponding QuestionnaireTemplate is found in Bumbal, an update will be performed.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.set_questionnaire_template(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param QuestionnaireTemplateModel body: QuestionnaireTemplate object
        :return: ApiResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.set_questionnaire_template_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.set_questionnaire_template_with_http_info(**kwargs)  # noqa: E501
            return data

    def set_questionnaire_template_with_http_info(self, **kwargs):  # noqa: E501
        """Set (create or update) a QuestionnaireTemplate  # noqa: E501

        Set (create or update) a d=QuestionnaireTemplate. If id or links are set in the data, and a corresponding QuestionnaireTemplate is found in Bumbal, an update will be performed.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.set_questionnaire_template_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param QuestionnaireTemplateModel body: QuestionnaireTemplate object
        :return: ApiResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method set_questionnaire_template" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key', 'jwt']  # noqa: E501

        return self.api_client.call_api(
            '/questionnaire-template/set', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ApiResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_questionnaire_template(self, questionnaire_template_id, **kwargs):  # noqa: E501
        """Update a specific QuestionnaireTemplate object  # noqa: E501

        Update a specific QuestionnaireTemplate object  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_questionnaire_template(questionnaire_template_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int questionnaire_template_id: ID of the QuestionnaireTemplate object to update (required)
        :param QuestionnaireTemplateModel body: QuestionnaireTemplate object that needs to be updated
        :return: ApiResponse30
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.update_questionnaire_template_with_http_info(questionnaire_template_id, **kwargs)  # noqa: E501
        else:
            (data) = self.update_questionnaire_template_with_http_info(questionnaire_template_id, **kwargs)  # noqa: E501
            return data

    def update_questionnaire_template_with_http_info(self, questionnaire_template_id, **kwargs):  # noqa: E501
        """Update a specific QuestionnaireTemplate object  # noqa: E501

        Update a specific QuestionnaireTemplate object  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_questionnaire_template_with_http_info(questionnaire_template_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int questionnaire_template_id: ID of the QuestionnaireTemplate object to update (required)
        :param QuestionnaireTemplateModel body: QuestionnaireTemplate object that needs to be updated
        :return: ApiResponse30
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['questionnaire_template_id', 'body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_questionnaire_template" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'questionnaire_template_id' is set
        if self.api_client.client_side_validation and ('questionnaire_template_id' not in params or
                                                       params['questionnaire_template_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `questionnaire_template_id` when calling `update_questionnaire_template`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'questionnaire_template_id' in params:
            path_params['questionnaire-templateId'] = params['questionnaire_template_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key', 'jwt']  # noqa: E501

        return self.api_client.call_api(
            '/questionnaire-template/{questionnaire-templateId}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ApiResponse30',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
