# coding: utf-8

"""
    Bumbal Client Api

    Bumbal API documentation  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: gerb@bumbal.eu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from bumbal.api_client import ApiClient


class VehicleTypeApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def create_vehicle_type(self, **kwargs):  # noqa: E501
        """Add a new VehicleType  # noqa: E501

        Add a new VehicleType  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_vehicle_type(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param VehicleTypeModel body: VehicleType object that needs to be created
        :return: VehicleTypeCreateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_vehicle_type_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.create_vehicle_type_with_http_info(**kwargs)  # noqa: E501
            return data

    def create_vehicle_type_with_http_info(self, **kwargs):  # noqa: E501
        """Add a new VehicleType  # noqa: E501

        Add a new VehicleType  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_vehicle_type_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param VehicleTypeModel body: VehicleType object that needs to be created
        :return: VehicleTypeCreateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_vehicle_type" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key', 'jwt']  # noqa: E501

        return self.api_client.call_api(
            '/vehicle-type', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='VehicleTypeCreateResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_vehicle_type(self, vehicle_type_id, **kwargs):  # noqa: E501
        """Delete a VehicleType entry  # noqa: E501

        Delete a VehicleType entry  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_vehicle_type(vehicle_type_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int vehicle_type_id: ID of VehicleType to delete (required)
        :return: VehicleTypeDeleteResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_vehicle_type_with_http_info(vehicle_type_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_vehicle_type_with_http_info(vehicle_type_id, **kwargs)  # noqa: E501
            return data

    def delete_vehicle_type_with_http_info(self, vehicle_type_id, **kwargs):  # noqa: E501
        """Delete a VehicleType entry  # noqa: E501

        Delete a VehicleType entry  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_vehicle_type_with_http_info(vehicle_type_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int vehicle_type_id: ID of VehicleType to delete (required)
        :return: VehicleTypeDeleteResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['vehicle_type_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_vehicle_type" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'vehicle_type_id' is set
        if self.api_client.client_side_validation and ('vehicle_type_id' not in params or
                                                       params['vehicle_type_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `vehicle_type_id` when calling `delete_vehicle_type`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'vehicle_type_id' in params:
            path_params['vehicleTypeId'] = params['vehicle_type_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key', 'jwt']  # noqa: E501

        return self.api_client.call_api(
            '/vehicle-type/{vehicleTypeId}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='VehicleTypeDeleteResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def retrieve_list_vehicle_type(self, arguments, **kwargs):  # noqa: E501
        """Retrieve List of VehicleTypes  # noqa: E501

        Retrieve List of VehicleTypes  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.retrieve_list_vehicle_type(arguments, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param VehicleTypeRetrieveListArguments arguments: VehicleType RetrieveList Arguments (required)
        :return: VehicleTypeListResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.retrieve_list_vehicle_type_with_http_info(arguments, **kwargs)  # noqa: E501
        else:
            (data) = self.retrieve_list_vehicle_type_with_http_info(arguments, **kwargs)  # noqa: E501
            return data

    def retrieve_list_vehicle_type_with_http_info(self, arguments, **kwargs):  # noqa: E501
        """Retrieve List of VehicleTypes  # noqa: E501

        Retrieve List of VehicleTypes  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.retrieve_list_vehicle_type_with_http_info(arguments, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param VehicleTypeRetrieveListArguments arguments: VehicleType RetrieveList Arguments (required)
        :return: VehicleTypeListResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['arguments']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method retrieve_list_vehicle_type" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'arguments' is set
        if self.api_client.client_side_validation and ('arguments' not in params or
                                                       params['arguments'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `arguments` when calling `retrieve_list_vehicle_type`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'arguments' in params:
            body_params = params['arguments']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key', 'jwt']  # noqa: E501

        return self.api_client.call_api(
            '/vehicle-type', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='VehicleTypeListResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def retrieve_vehicle_type(self, provider_id, **kwargs):  # noqa: E501
        """Retrieve a VehicleType  # noqa: E501

        Retrieve an VehicleType  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.retrieve_vehicle_type(provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int provider_id: ID of VehicleType to retrieve (required)
        :return: VehicleTypeModel
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.retrieve_vehicle_type_with_http_info(provider_id, **kwargs)  # noqa: E501
        else:
            (data) = self.retrieve_vehicle_type_with_http_info(provider_id, **kwargs)  # noqa: E501
            return data

    def retrieve_vehicle_type_with_http_info(self, provider_id, **kwargs):  # noqa: E501
        """Retrieve a VehicleType  # noqa: E501

        Retrieve an VehicleType  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.retrieve_vehicle_type_with_http_info(provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int provider_id: ID of VehicleType to retrieve (required)
        :return: VehicleTypeModel
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['provider_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method retrieve_vehicle_type" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'provider_id' is set
        if self.api_client.client_side_validation and ('provider_id' not in params or
                                                       params['provider_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `provider_id` when calling `retrieve_vehicle_type`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'provider_id' in params:
            path_params['providerId'] = params['provider_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key', 'jwt']  # noqa: E501

        return self.api_client.call_api(
            '/vehicle-type/{vehicleTypeId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='VehicleTypeModel',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_vehicle_type(self, vehicle_type_id, **kwargs):  # noqa: E501
        """Update a specific VehicleType object  # noqa: E501

        Update a specific VehicleType object  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_vehicle_type(vehicle_type_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int vehicle_type_id: ID of the VehicleType object to update (required)
        :param VehicleTypeModel body: VehicleType object that needs to be updated
        :return: VehicleTypeUpdateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.update_vehicle_type_with_http_info(vehicle_type_id, **kwargs)  # noqa: E501
        else:
            (data) = self.update_vehicle_type_with_http_info(vehicle_type_id, **kwargs)  # noqa: E501
            return data

    def update_vehicle_type_with_http_info(self, vehicle_type_id, **kwargs):  # noqa: E501
        """Update a specific VehicleType object  # noqa: E501

        Update a specific VehicleType object  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_vehicle_type_with_http_info(vehicle_type_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int vehicle_type_id: ID of the VehicleType object to update (required)
        :param VehicleTypeModel body: VehicleType object that needs to be updated
        :return: VehicleTypeUpdateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['vehicle_type_id', 'body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_vehicle_type" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'vehicle_type_id' is set
        if self.api_client.client_side_validation and ('vehicle_type_id' not in params or
                                                       params['vehicle_type_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `vehicle_type_id` when calling `update_vehicle_type`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'vehicle_type_id' in params:
            path_params['vehicleTypeId'] = params['vehicle_type_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key', 'jwt']  # noqa: E501

        return self.api_client.call_api(
            '/vehicle-type/{vehicleTypeId}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='VehicleTypeUpdateResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
